### ISSUE TITLE
Error on baby shoes with special attributes self.web_select(By.XPATH, f"//select[@id='{special_attribute_key}']", special_attribute_value)

### ISSUE THREAD

**Issue by inspirationally** [Second-Hand-Friends/kleinanzeigen-bot#156]
Hello, in the category shoes (baby shoes) I always get this error - it crashes right after choosing category and special attribute with this error in the Terminal (MacOS)

`
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/**//kleinanzeigen-bot/kleinanzeigen_bot/__main__.py", line 8, in <module>
    kleinanzeigen_bot.main(sys.argv)
  File "/Users/**//kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 660, in main
    KleinanzeigenBot().run(args)
  File "/Users/**//kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 78, in run
    self.publish_ads(ads)
  File "/Users/**//kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 410, in publish_ads
    self.publish_ad(ad_file, ad_cfg, ad_cfg_orig)
  File "/Users/**//kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 442, in publish_ad
    self.__set_category(ad_file, ad_cfg)
  File "/Users/**/kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 578, in __set_category
    self.web_select(By.XPATH, f"//select[@id='{special_attribute_key}']", special_attribute_value)
  File "/Users/**//kleinanzeigen-bot/kleinanzeigen_bot/selenium_mixin.py", line 365, in web_select
    Select(elem).select_by_value(selected_value)
  File "/Users/**//kleinanzeigen-bot/__pypackages__/3.10/lib/selenium/webdriver/support/select.py", line 76, in select_by_value
    css = "option[value =%s]" % self._escape_string(value)
  File "/Users/**//kleinanzeigen-bot/__pypackages__/3.10/lib/selenium/webdriver/support/select.py", line 219, in _escape_string
    if '"' in value and "'" in value:
TypeError: argument of type 'int' is not iterable
`

It seems to have something to do with the special_attribute_key, so I went to the website and double checked that the field is really called like that. It did work before, at about 2 months ago.

One example of my ads config:

`title: Keen Seacamp Sandalen 34 pink rosa Mädchen wie newport moxie
description: Ich verkaufe hier Keen Newport Sandalen in Gr. 34. Gern getragen siehe Bilder, einziger Defekt ist beim rechten Schuh vorn der Stoff, dort ist eine Schicht des Stoffes durch. Ein Fleck an der Ferse links ging nicht raus. Fällt wie immer bei Keen 1 Nummer kleiner aus.\n\n\
category: 17/19/sandalen
special_attributes: {baby_kinderschuhe.groesse_s: 34}
sell_directly: false
price: 10
price_type: NEGOTIABLE # one of: FIXED, NEGOTIABLE, GIVE_AWAY, NOT_APPLICABLE
shipping_type: SHIPPING # one of: PICKUP, SHIPPING, NOT_APPLICABLE
shipping_costs: 6
images:
  - images/keen-seacamp-34/keen-newport-34 - 1.jpeg`
  
Any ideas?

**Comment by inspirationally** [comment]
I could solve myself by wrapping it into " like so:
special_attributes: {"baby_kinderschuhe.groesse_s": "34"}
