### ISSUE TITLE
Error: NoSuchElementException: Message: Element xpath://*[@id='postad-step1-sbmt']/button not found or not clickable

### ISSUE THREAD

**Issue by lamyergeier** [Second-Hand-Friends/kleinanzeigen-bot#176]
```
 _    _      _                           _                       _           _
| | _| | ___(_)_ __   __ _ _ __  _______(_) __ _  ___ _ __      | |__   ___ | |_
| |/ / |/ _ \ | '_ \ / _` | '_ \|_  / _ \ |/ _` |/ _ \ '_ \ ____| '_ \ / _ \| __|
|   <| |  __/ | | | | (_| | | | |/ /  __/ | (_| |  __/ | | |____| |_) | (_) | |_
|_|\_\_|\___|_|_| |_|\__,_|_| |_/___\___|_|\__, |\___|_| |_|    |_.__/ \___/ \__|
                                           |___/
                         https://github.com/Second-Hand-Friends/kleinanzeigen-bot

[INFO] Logging to [/mnt/Documents/Mobile/Data/Task/Todo/Sales/kleinanzeigen-bot.log]...
[INFO] App version: 0.1.dev1+gb82b1f7
[INFO] Loading config from [/home/lamy/opt/Kleinanzeigen/config.yaml]...
[INFO]  -> found 138 categories
[INFO] Searching for ad config files...
[INFO]  -> found 2 ad config files
[INFO] Loading ad from [/home/lamy/Documents/Mobile/Data/Task/Todo/Sales/Bike/ad_Bike.yaml]...
[INFO] Loading ad from [/home/lamy/Documents/Mobile/Data/Task/Todo/Sales/Macbook/ad_Laptop.yaml]...
[INFO] Loaded 2 ads
[INFO] Creating WebDriver session...
[INFO] Using pre-installed Chrome Driver [/usr/bin/chromedriver]
[INFO]  -> Custom chrome argument: --user-agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0
[INFO]  -> Custom chrome argument: --disable-dev-shm-usage
[INFO]  -> Custom chrome argument: --no-sandbox
[INFO] New WebDriver session is: 5ce5eb05ced28ee88806ab68d5a400c2 http://localhost:44035
[INFO] Logging in as [lamyergeier@gmail.com]...
[INFO]  ... pausing for 2000 ms ...
[INFO]  ... pausing for 1959 ms ...
[WARNING] ############################################
[WARNING] # Captcha present! Please solve and close the captcha, but DON'T click 'Einloggen'.
[WARNING] ############################################
[INFO] Processing 1/2: 'Mountain Bike Fully Functional 27.5 inch' from [/home/lamy/Documents/Mobile/Data/Task/Todo/Sales/Bike/ad_Bike.yaml]...
[INFO] Deleting ad 'Mountain Bike Fully Functional 27.5 inch' if already present...
[INFO]  ... pausing for 2000 ms ...
[INFO]  ... pausing for 2130 ms ...
[INFO] Publishing ad 'Mountain Bike Fully Functional 27.5 inch'...
[INFO]  ... pausing for 2000 ms ...
[INFO]  ... pausing for 1890 ms ...
[INFO]  ... pausing for 1600 ms ...
[INFO]  ... pausing for 2000 ms ...
[INFO]  ... pausing for 1726 ms ...
[INFO]  ... pausing for 2000 ms ...
[ERROR] NoSuchElementException: Message: Element xpath://*[@id='postad-step1-sbmt']/button not found or not clickable
```

**Comment by xax** [comment]
To add more verbose info:
```
Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 8, in <module>
  File "kleinanzeigen_bot\__init__.py", line 991, in main
  File "kleinanzeigen_bot\__init__.py", line 80, in run
  File "kleinanzeigen_bot\__init__.py", line 438, in publish_ads
  File "kleinanzeigen_bot\__init__.py", line 470, in publish_ad
  File "kleinanzeigen_bot\__init__.py", line 606, in __set_category
  File "kleinanzeigen_bot\selenium_mixin.py", line 267, in web_click
  File "kleinanzeigen_bot\selenium_mixin.py", line 249, in web_await
selenium.common.exceptions.NoSuchElementException: Message: Element xpath://*[@id='postad-step1-sbmt']/button not found or not clickable
```

… for what it's worth, there *is* a `button` inside an `.postad-step1-sbmt`, in the categories selector, though...
