### ISSUE TITLE
Error when installing selenium

### ISSUE THREAD

**Issue by johannesschweig** [Second-Hand-Friends/kleinanzeigen-bot#20]
I get the following stacktrace when trying to install selenium with pip (pip install -t __pypackages__/3.10/lib selenium).
`ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/home/nash/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/nash/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/nash/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 147, in _add_to_criteria
    matches = self._p.find_matches(
TypeError: PipProvider.find_matches() got an unexpected keyword argument 'identifier'`

OS: arch

**Comment by sebthom** [comment]
This is not an issue of this app but with your local python installation. either wrong python or pip version or some issue in the already installed pip packages. You can check the logs of our CI builds which work on Windows, Mac and Linux to see what is different on your system.

**Comment by johannesschweig** [comment]
In the end it was a permission problem. Just couldn't figure that out from the stacktrace.

**Comment by sebthom** [comment]
How didn't you figure it out. Any advices for other users that may hit the same issue?

**Comment by johannesschweig** [comment]
I am sorry, but no. I am still in the process of figuring out how to setup the repo, so that it runs on my machine.
