### ISSUE TITLE
pdm install issue: module '_distutils_hack' has no attribute 'add_shim'

### ISSUE THREAD

**Issue by Airwave1981** [Second-Hand-Friends/kleinanzeigen-bot#227]
After reinstalling and then running 

1. pip install pdm

i get with 2. "pdm install"
following errors.

Anyone has an idea,whats wrong in distutils-precedence.pth?

Thanks in advance.

```
E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot>pdm install
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Synchronizing working set with lock file: 3 to add, 57 to update, 0 to remove

  - Updating setuptools 63.2.0 -> 68.2.2...Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
  - Updating setuptools 63.2.0 -> 68.2.2...Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  \ Updating setuptools 63.2.0 -> 68.2.2...  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
  - Updating setuptools 63.2.0 -> 68.2.2...Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
  \ Updating setuptools 63.2.0 -> 68.2.2...Error processing line 1 of E:\Google Drive\Verkauf\_auto\kleinanzeigen-bot\.venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
  x Update setuptools 63.2.0 -> 68.2.2 failed

See C:\Users\ADMINI~1\AppData\Local\Temp\pdm-install-1x8aq4oo.log for detailed debug log.
[UninstallError]: [WinError 5] Zugriff verweigert: 'e:\\google drive\\verkauf\\_auto\\kleinanzeigen-bot\\.venv\\lib\\site-packages\\pkg_resources\\extern'
Add '-v' to see the detailed traceback
```

**Comment by Airwave1981** [comment]
Okay complete uninstalling python and reinstalling cleared the issue. So could been closed. Just for information for others having this issue.
