### ISSUE TITLE
[BUG] ImportError: Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by mhmuc1** [Second-Hand-Friends/kleinanzeigen-bot#229]
### ✔️ Expected Behaviour

Login + Download of published ads

### 🐞 Actual Behaviour

Not starting, because of SSL-Error with edge or chrome on windows

### 📋 Steps to Reproduce

run the bot with "download" command

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

Windows

### 📃 Relevant log output (if applicable)

[INFO] Logging to [C:\Users\XXX\OneDrive\SYNC-Programme\KleinanzeigenBot\kleinanzeigen-bot.log]...
[INFO] App version: 0.1.dev1+gd932cbd
[WARNING] You provided no ads selector. Defaulting to "new".
[INFO] Loading config from [C:\Users\XXX\OneDrive\SYNC-Programme\KleinanzeigenBot\config.yaml]...
[INFO]  -> found 145 categories
[INFO] Creating WebDriver session...
[INFO] Using Browser: GOOGLE-CHROME 118.0.5993.118 [C:\Program Files\Google\Chrome\Application\chrome.exe]
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 9, in <module>
  File "kleinanzeigen_bot\__init__.py", line 1037, in main
  File "kleinanzeigen_bot\__init__.py", line 106, in run
  File "kleinanzeigen_bot\selenium_mixin.py", line 148, in create_webdriver_session
  File "webdriver_manager\chrome.py", line 40, in install
  File "webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path
  File "webdriver_manager\core\driver_cache.py", line 105, in find_driver
  File "webdriver_manager\core\driver_cache.py", line 152, in get_cache_key_driver_version
  File "webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
  File "webdriver_manager\drivers\chrome.py", line 59, in get_latest_release_version
  File "webdriver_manager\core\http.py", line 32, in get
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 770, in urlopen
  File "urllib3\connectionpool.py", line 296, in _get_conn
  File "urllib3\connectionpool.py", line 1061, in _new_conn
ImportError: Can't connect to HTTPS URL because the SSL module is not available.

[11260] Failed to execute script '__main__' due to unhandled exception!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hendrikator** [comment]
[INFO] Loaded 33 ads
[INFO] Creating WebDriver session...
[INFO] Using Browser: EDGE 118.0.2088.76 [C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe]
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 9, in <module>
  File "kleinanzeigen_bot\__init__.py", line 1037, in main
  File "kleinanzeigen_bot\__init__.py", line 80, in run
  File "kleinanzeigen_bot\selenium_mixin.py", line 139, in create_webdriver_session
  File "webdriver_manager\microsoft.py", line 73, in install
  File "webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path
  File "webdriver_manager\core\driver_cache.py", line 105, in find_driver
  File "webdriver_manager\core\driver_cache.py", line 152, in get_cache_key_driver_version
  File "webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
  File "webdriver_manager\drivers\edge.py", line 51, in get_latest_release_version
  File "webdriver_manager\core\http.py", line 32, in get
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 770, in urlopen
  File "urllib3\connectionpool.py", line 296, in _get_conn
  File "urllib3\connectionpool.py", line 1061, in _new_conn
ImportError: Can't connect to HTTPS URL because the SSL module is not available.

[27872] Failed to execute script '__main__' due to unhandled exception!

**Comment by SphaeroX** [comment]
Same Here:

```
[INFO] App version: 0.1.dev1+gd932cbd
[WARNING] You provided no ads selector. Defaulting to "new".
[INFO] Loading config from [C:\Users\XXX\config.yaml]...
[INFO]  -> found 145 categories
[INFO] Creating WebDriver session...
[INFO] Using Browser: EDGE 119.0.2151.58 [C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe]
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 9, in <module>
  File "kleinanzeigen_bot\__init__.py", line 1037, in main
  File "kleinanzeigen_bot\__init__.py", line 106, in run
  File "kleinanzeigen_bot\selenium_mixin.py", line 139, in create_webdriver_session
  File "webdriver_manager\microsoft.py", line 73, in install
  File "webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path
  File "webdriver_manager\core\driver_cache.py", line 105, in find_driver
  File "webdriver_manager\core\driver_cache.py", line 152, in get_cache_key_driver_version
  File "webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
  File "webdriver_manager\drivers\edge.py", line 51, in get_latest_release_version
  File "webdriver_manager\core\http.py", line 32, in get
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 770, in urlopen
  File "urllib3\connectionpool.py", line 296, in _get_conn
  File "urllib3\connectionpool.py", line 1061, in _new_conn
ImportError: Can't connect to HTTPS URL because the SSL module is not available.

[59116] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by dragonheart100** [comment]
+1

**Comment by mhmuc1** [comment]
Is there any chance for a fix anytime soon?
My adds are about to expire....

**Comment by zeus24** [comment]
Can confirm. Also with latest update
App version: 0.1.dev1+g55d8cc1
@sebthom

**Comment by SphaeroX** [comment]
latest release today got this error too. 

it seems Kleinanzeigen made there job...

**Comment by kriz99** [comment]
> it seems Kleinanzeigen made there job...

Can anyone confirm that it only affects the Windows version?

**Comment by sebthom** [comment]
I am on Windows 10 and cannot reproduce this issue. Is it happening with the self-contained exe and/or when running from source with `pdm run app` ?

**Comment by mhmuc1** [comment]
I am on win 11 64bit with provided exe

**Comment by SphaeroX** [comment]
Win11 Here too

**Comment by zeus24** [comment]
Win 10. I am using the provided exe.

**Comment by kriz99** [comment]
Im using the **pre-compiled exe** App version: 0.1.dev1+g55d8cc1, the problem exists on:
Windows 10 Version 22H2, EDGE 120.0.2210.61 and
Windows 11

**Comment by SphaeroX** [comment]
Betriebsystemname	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
Bot Release: latest


```
[INFO]  -> found 145 categories
[INFO] Creating WebDriver session...
[INFO] Using Browser: EDGE 120.0.2210.61 [C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe]
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 9, in <module>
  File "kleinanzeigen_bot\__init__.py", line 1037, in main
  File "kleinanzeigen_bot\__init__.py", line 106, in run
  File "kleinanzeigen_bot\selenium_mixin.py", line 138, in create_webdriver_session
  File "webdriver_manager\microsoft.py", line 73, in install
  File "webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path
  File "webdriver_manager\core\driver_cache.py", line 105, in find_driver
  File "webdriver_manager\core\driver_cache.py", line 152, in get_cache_key_driver_version
  File "webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
  File "webdriver_manager\drivers\edge.py", line 51, in get_latest_release_version
  File "webdriver_manager\core\http.py", line 32, in get
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 769, in urlopen
  File "urllib3\connectionpool.py", line 295, in _get_conn
  File "urllib3\connectionpool.py", line 1060, in _new_conn
ImportError: Can't connect to HTTPS URL because the SSL module is not available.

[30816] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by dragonheart100** [comment]
Windows 10 22H2 19045.3693
*.exe Version 0.1.dev1+gc7e8869
Still the same problem.

The pdm run app starts, but there I have problems with the new captcha  #219

**Comment by TylonHH** [comment]
even with **Chrome**

```←[1;30m[INFO]←[0m Using Browser: GOOGLE-CHROME 120.0.6099.110 [C:\Program Files\Google\Chrome\Application\chrome.exe]
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 9, in <module>
  File "kleinanzeigen_bot\__init__.py", line 1045, in main
  File "kleinanzeigen_bot\__init__.py", line 112, in run
  File "kleinanzeigen_bot\selenium_mixin.py", line 147, in create_webdriver_session
  File "webdriver_manager\chrome.py", line 40, in install
  File "webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path
  File "webdriver_manager\core\driver_cache.py", line 105, in find_driver
  File "webdriver_manager\core\driver_cache.py", line 152, in get_cache_key_driver_version
  File "webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
  File "webdriver_manager\drivers\chrome.py", line 59, in get_latest_release_version
  File "webdriver_manager\core\http.py", line 32, in get
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 769, in urlopen
  File "urllib3\connectionpool.py", line 295, in _get_conn
  File "urllib3\connectionpool.py", line 1060, in _new_conn
ImportError: Can't connect to HTTPS URL because the SSL module is not available.

[7636] Failed to execute script '__main__' due to unhandled exception!```

**Comment by statementer** [comment]
I have the same error on edge and chrome will there be a fix?

I tried to use linux and i cannot log in because i cannot get past the captcha. I think it would work if the bot doesnt start in icognito mode and one has logged on the browser so the bot detects the cookies and logs in via them. Is there a way to not start the bot in icognito mode?

**Comment by ghoeffner** [comment]
This issue on Windows still persists with the latest build.

**Comment by hendrikator** [comment]
jup same

[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 9, in <module>
  File "kleinanzeigen_bot\__init__.py", line 1064, in main
  File "kleinanzeigen_bot\__init__.py", line 91, in run
  File "kleinanzeigen_bot\selenium_mixin.py", line 147, in create_webdriver_session
  File "webdriver_manager\chrome.py", line 40, in install
  File "webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path
  File "webdriver_manager\core\driver_cache.py", line 105, in find_driver
  File "webdriver_manager\core\driver_cache.py", line 152, in get_cache_key_driver_version
  File "webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
  File "webdriver_manager\drivers\chrome.py", line 59, in get_latest_release_version
  File "webdriver_manager\core\http.py", line 32, in get
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 769, in urlopen
  File "urllib3\connectionpool.py", line 295, in _get_conn
  File "urllib3\connectionpool.py", line 1060, in _new_conn
ImportError: Can't connect to HTTPS URL because the SSL module is not available.

[25064] Failed to execute script '__main__' due to unhandled exception!

**Comment by kriz99** [comment]
> jup same

Can confirm: App version: 0.1.dev1+gfcd24c9 doesn't work

**Comment by dax228** [comment]
Can confirm :
Same problem on Windows 11.

No problem on Ubuntu (althought there is at least 3 other problems which wont make this work)
