### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by euberdeveloper** [Second-Hand-Friends/kleinanzeigen-bot#259]
### ✔️ Expected Behaviour

The bot should work

### 🐞 Actual Behaviour

The captcha blocks the bot

### 📋 Steps to Reproduce

[INFO] App version: 2024+52f76f1
[INFO] Python version: 3.12.1 (main, Dec  8 2023, 05:40:51) [GCC 11.4.0]

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IchSkill** [comment]
The Bot gets banned and crashes, right?

**Comment by euberdeveloper** [comment]
I think it's the same of issue #219

**Comment by euberdeveloper** [comment]
No need to say that this is not a fix but just a workaround

**Comment by euberdeveloper** [comment]
This has more details #219

* Open manually the browser that you will use for the bot
* Login to your Kleinanzeigen accounts
* After the login, some session info will be saved in the (presumingly) chrome userd data folder
* You can tell to the bot to use that folder for the selenium/bot session, so that the login is not needed (and hence not blocked)
* So go to the config.yml and set that folder as user_data_dir [here the usual location](https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md) + do not use private mode

**Comment by Heart1010** [comment]
This is what I'm getting as error:
```bash
> pdm run app download --config=config.yaml -v           02/12/24 15:56:15 PM

 _    _      _                           _                       _           _
| | _| | ___(_)_ __   __ _ _ __  _______(_) __ _  ___ _ __      | |__   ___ | |_
| |/ / |/ _ \ | '_ \ / _` | '_ \|_  / _ \ |/ _` |/ _ \ '_ \ ____| '_ \ / _ \| __|
|   <| |  __/ | | | | (_| | | | |/ /  __/ | (_| |  __/ | | |____| |_) | (_) | |_
|_|\_\_|\___|_|_| |_|\__,_|_| |_/___\___|_|\__, |\___|_| |_|    |_.__/ \___/ \__|
                                           |___/
                         https://github.com/Second-Hand-Friends/kleinanzeigen-bot

[INFO] Logging to [P:\Projekte\kleinanzeigen\kleinanzeigen-bot\kleinanzeigen_bot.log]...
[INFO] App version: 0.0.0
[WARNING] You provided no ads selector. Defaulting to "new".
[DEBUG] Loading [kleinanzeigen_bot.resources.config_defaults.yaml]...
[INFO] Loading config from [P:\Projekte\kleinanzeigen\kleinanzeigen-bot\config.yaml]...
[DEBUG] Loading categories from [kleinanzeigen_bot.resources.categories.yaml]...
[INFO]  -> found 145 categories
[INFO] Creating WebDriver session...
[INFO] Using Browser: GOOGLE-CHROME 121.0.6167.161 [C:\Program Files\Google\Chrome\Application\chrome.exe]
[INFO]  -> Browser User Data Dir: C:\Users\Hermann\AppData\Local\Google\Chrome\User Data\
[INFO]  -> Browser Profile Name: Default
[INFO]  -> Custom chrome argument: --disable-gpu
[INFO]  -> Custom chrome argument: --disable-dev-shm-usage
[INFO]  -> Custom chrome argument: --no-sandbox
[INFO]  -> Custom chrome argument: --disable-setuid-sandbox
[INFO]  -> Custom chrome argument: --disable-extensions
[INFO]  -> Custom chrome argument: --disable-application-cache
[DEBUG] Effective browser arguments: ['--user-data-dir=C:\\Users\\Hermann\\AppData\\Local\\Google\\Chrome\\User Data\\', '--profile-directory=Default', '--disable-crash-reporter', '--no-first-run', '--no-service-autorun', '--disable-gpu', '--disable-dev-shm-usage', '--no-sandbox', '--disable-setuid-sandbox', '--disable-extensions', '--disable-application-cache']
[DEBUG] Effective browser extensions: []
[DEBUG] Effective experimental options: {}
[INFO]  -> Chrome binary location: C:\Program Files\Google\Chrome\Application\chrome.exe
[ERROR] Traceback (most recent call last):
  File "C:\Users\Hermann\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Hermann\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\kleinanzeigen_bot\__main__.py", line 9, in <module>
    kleinanzeigen_bot.main(sys.argv)
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\kleinanzeigen_bot\__init__.py", line 1040, in main
    KleinanzeigenBot().run(args)
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\kleinanzeigen_bot\__init__.py", line 106, in run
    self.create_webdriver_session()
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\kleinanzeigen_bot\selenium_mixin.py", line 151, in create_webdriver_session
    self.webdriver = uc.Chrome(service = ChromeService(webdriver_path), options = self._init_browser_options(webdriver.ChromeOptions()))
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\.venv\lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\.venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\.venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\.venv\lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "P:\Projekte\kleinanzeigen\kleinanzeigen-bot\.venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:55792
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x01091673+52979]
        (No symbol) [0x01017961]
        (No symbol) [0x00EFDC00]
        (No symbol) [0x00EF1D83]
        (No symbol) [0x00F28CE9]
        (No symbol) [0x00F213F5]
        (No symbol) [0x00F21227]
        (No symbol) [0x00F5D2B1]
        (No symbol) [0x00F5CE5A]
        (No symbol) [0x00F54286]
        (No symbol) [0x00F2C063]
        (No symbol) [0x00F2CECD]
        GetHandleVerifier [0x013A8D83+3294723]
        GetHandleVerifier [0x013E6CC2+3548482]
        GetHandleVerifier [0x013E1C9C+3527964]
        GetHandleVerifier [0x0112870E+671630]
        (No symbol) [0x01021EB4]
        (No symbol) [0x0101D808]
        (No symbol) [0x0101D92D]
        (No symbol) [0x0100F7E0]
        BaseThreadInitThunk [0x75B6FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77747C5E+286]
        RtlGetAppContainerNamedObjectPath [0x77747C2E+238]


P:/Projekte/kleinanzeigen/kleinanzeigen-bot>
```

**Comment by Synzed** [comment]
> This has more details #219
> 
> * Open manually the browser that you will use for the bot
> * Login to your Kleinanzeigen accounts
> * After the login, some session info will be saved in the (presumingly) chrome userd data folder
> * You can tell to the bot to use that folder for the selenium/bot session, so that the login is not needed (and hence not blocked)
> * So go to the config.yml and set that folder as user_data_dir [here the usual location](https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md) + do not use private mode

doesnt solve it for me, still opens the browser in a new window with a fresh profile = get blocked again

**Comment by euberdeveloper** [comment]
> > This has more details #219
> > 
> > * Open manually the browser that you will use for the bot
> > * Login to your Kleinanzeigen accounts
> > * After the login, some session info will be saved in the (presumingly) chrome userd data folder
> > * You can tell to the bot to use that folder for the selenium/bot session, so that the login is not needed (and hence not blocked)
> > * So go to the config.yml and set that folder as user_data_dir [here the usual location](https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md) + do not use private mode
> 
> doesnt solve it for me, still opens the browser in a new window with a fresh profile = get blocked again

Then you are doing something wrong, it is possible to open it with a new profile

**Comment by shukui** [comment]
> This has more details #219
> 
> * Open manually the browser that you will use for the bot
> * Login to your Kleinanzeigen accounts
> * After the login, some session info will be saved in the (presumingly) chrome userd data folder
> * You can tell to the bot to use that folder for the selenium/bot session, so that the login is not needed (and hence not blocked)
> * So go to the config.yml and set that folder as user_data_dir [here the usual location](https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md) + do not use private mode

Thanks a lot.
I tried this and got a WebDriverException 
![image](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/assets/20155911/a38e9a17-0ab2-42d8-af5e-aaceb1f83c3a)

**Comment by sebthom** [comment]
Should be solved by latest release
