### ISSUE TITLE
[BUG] Failed to connect to browser

### ISSUE THREAD

**Issue by finnjung** [Second-Hand-Friends/kleinanzeigen-bot#326]
### ✔️ Expected Behaviour

Connect to browser when executed

### 🐞 Actual Behaviour

Terminal: 
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot/__main__.py", line 9, in <module>
  File "kleinanzeigen_bot/__init__.py", line 902, in main
  File "asyncio/base_events.py", line 684, in run_until_complete
  File "kleinanzeigen_bot/__init__.py", line 91, in run
  File "kleinanzeigen_bot/web_scraping_mixin.py", line 201, in create_browser_session
  File "nodriver/core/util.py", line 88, in start
  File "nodriver/core/browser.py", line 91, in create
  File "nodriver/core/browser.py", line 351, in start
Exception: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 

### 📋 Steps to Reproduce

I run the executable version on a Mac currently with chrome, but I also tried edge and there was the same problem

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome, Microsoft Edge

### 💻 What operating systems are you seeing the problem on? (if applicable)

MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebthom** [comment]
Closing this as duplicate of #315 where some suggestions are provided in comments.
