### ISSUE TITLE
[BUG] TimeoutError: No HTML element found with ID 'checking-done' within 5 seconds.

### ISSUE THREAD

**Issue by student-sx** [Second-Hand-Friends/kleinanzeigen-bot#351]
### ✔️ Expected Behaviour

Successfully uploading multiple ads.

### 🐞 Actual Behaviour

After the first ad is uploaded it crashes with "TimeoutError: No HTML element found with ID 'checking-done' within 5 seconds."

### 📋 Steps to Reproduce

```
./kleinanzeigen-bot --verbose --ads=due publish
```
Bot Version: 2024+26f05b5

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

Linux

### 📃 Relevant log output (if applicable)

```
 -> uploading image [/home/myuser/kleinanzeigen-bot/downloaded-ads/ad_2840818434/ad_2840818434__img2.jpg]
[DEBUG]  ... pausing for 1369 ms ...
[INFO]  ... pausing for 2233 ms ...
[INFO]  -> SUCCESS: ad published with ID 2933348675
[INFO] Saving [/home/myuser/kleinanzeigen-bot/downloaded-ads/ad_2840818434/ad_2840818434.yaml]...
[INFO] Deleting ad 'Meine Anzeige 2' if already present...
[DEBUG]  -> Opening [https://www.kleinanzeigen.de/m-meine-anzeigen.html]...
[DEBUG]  -> HTTP POST [https://www.kleinanzeigen.de/m-anzeigen-loeschen.json?ids=2864273779]...
[DEBUG]  ... pausing for 1158 ms ...
[DEBUG] Closing Browser session...
[INFO] terminated browser with pid 11070 successfully
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot/__main__.py", line 9, in <module>
  File "kleinanzeigen_bot/__init__.py", line 945, in main
  File "asyncio/base_events.py", line 721, in run_until_complete
  File "kleinanzeigen_bot/__init__.py", line 92, in run
  File "kleinanzeigen_bot/__init__.py", line 507, in publish_ads
  File "kleinanzeigen_bot/web_scraping_mixin.py", line 284, in web_await
  File "kleinanzeigen_bot/web_scraping_mixin.py", line 277, in web_await
  File "kleinanzeigen_bot/web_scraping_mixin.py", line 310, in web_check
  File "kleinanzeigen_bot/web_scraping_mixin.py", line 363, in web_find
  File "kleinanzeigen_bot/web_scraping_mixin.py", line 285, in web_await
TimeoutError: No HTML element found with ID 'checking-done' within 5 seconds.

[PYI-11069:ERROR] Failed to execute script '__main__' due to unhandled exception!
[INFO] terminated browser with pid 11070 successfully
successfully removed temp profile /tmp/uc_e0w51kbo
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IchSkill** [comment]
facing the same problem. It is publishing one ad succesfully then crashing with your symptoms
