### ISSUE TITLE
[BUG] TimeoutError: No HTML element found using CSS selector '[class*="jsx-2623555103"]' within 5 seconds.

### ISSUE THREAD

**Issue by Perederey** [Second-Hand-Friends/kleinanzeigen-bot#353]
### ✔️ Expected Behaviour

`./kleinanzeigen-bot publish --ads=due --verbose`

### 🐞 Actual Behaviour

TimeoutError: No HTML element found using CSS selector '[class*="jsx-2623555103"]' within 5 seconds.

### 📋 Steps to Reproduce

1) download ads
2) try to republish

more info in logs

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

MacOS

### 📃 Relevant log output (if applicable)

```bash

 _    _      _                           _                       _           _
| | _| | ___(_)_ __   __ _ _ __  _______(_) __ _  ___ _ __      | |__   ___ | |_
| |/ / |/ _ \ | '_ \ / _` | '_ \|_  / _ \ |/ _` |/ _ \ '_ \ ____| '_ \ / _ \| __|
|   <| |  __/ | | | | (_| | | | |/ /  __/ | (_| |  __/ | | |____| |_) | (_) | |_
|_|\_\_|\___|_|_| |_|\__,_|_| |_/___\___|_|\__, |\___|_| |_|    |_.__/ \___/ \__|
                                           |___/
                         https://github.com/Second-Hand-Friends/kleinanzeigen-bot

[INFO] Logging to [/Users/sasha/code/kleinanzeigen/kleinanzeigen-bot.log]...
[INFO] App version: 2024+26f05b5
[INFO] Python version: 3.13.0 (v3.13.0:60403a5409f, Oct  7 2024, 00:37:40) [Clang 15.0.0 (clang-1500.3.9.4)]
[DEBUG] Loading [kleinanzeigen_bot.resources.config_defaults.yaml]...
[INFO] Loading config from [/Users/sasha/code/kleinanzeigen/config.yaml]...
[DEBUG] Loading categories from [kleinanzeigen_bot.resources.categories.yaml]...
[DEBUG] Loading categories from [kleinanzeigen_bot.resources.categories_old.yaml]...
[INFO]  -> found 665 categories
[INFO] Searching for ad config files...
[INFO]  -> found 20 ad config files
[DEBUG] Loading [kleinanzeigen_bot.resources.ad_fields.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907194386/ad_2907194386.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907262949/ad_2907262949.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907265939/ad_2907265939.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907268732/ad_2907268732.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907939476/ad_2907939476.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907947762/ad_2907947762.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907953604/ad_2907953604.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907955876/ad_2907955876.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907962632/ad_2907962632.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907965525/ad_2907965525.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907971121/ad_2907971121.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907973149/ad_2907973149.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907974781/ad_2907974781.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2913184084/ad_2913184084.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2913186285/ad_2913186285.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2913188301/ad_2913188301.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2914708210/ad_2914708210.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2916666844/ad_2916666844.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2916668656/ad_2916668656.yaml]...
[INFO] Loading ad from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2927805396/ad_2927805396.yaml]...
[INFO] Loaded 20 ads
[INFO] Creating Browser session...
[INFO]  -> Chrome binary location: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[INFO] Using existing browser process at 127.0.0.1:9223
[INFO] starting
	executable :/Applications/Google Chrome.app/Contents/MacOS/Google Chrome

arguments:
--remote-allow-origins=*
	--no-first-run
	--no-service-autorun
	--no-default-browser-check
	--homepage=about:blank
	--no-pings
	--password-store=basic
	--disable-infobars
	--disable-breakpad
	--disable-component-update
	--disable-backgrounding-occluded-windows
	--disable-renderer-backgrounding
	--disable-background-networking
	--disable-dev-shm-usage
	--disable-features=IsolateOrigins,site-per-process
	--disable-session-crashed-bubble
	--disable-search-engine-choice-screen
	--user-data-dir=/var/folders/5_/3s57744n5mn067f_87cxytrc0000gn/T/uc_p0qlnwhf
	--disable-features=IsolateOrigins,site-per-process
	--disable-session-crashed-bubble
	--remote-debugging-host=127.0.0.1
	--remote-debugging-port=9223
[INFO] enabling autodiscover targets
[INFO] New Browser session is ws://127.0.0.1:9223/devtools/browser/19460fc5-bcd2-43bc-aa0e-53496505d28f
[INFO] Checking if already logged in...
[DEBUG]  -> Opening [https://www.kleinanzeigen.de]...
[INFO] Already logged in as [xxxxxx]. Skipping login.
[INFO] Processing 1/20: 'iPhone 14 Pro, 128gb (als Neu!)' from [/Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907194386/ad_2907194386.yaml]...
[INFO] Publishing ad 'iPhone 14 Pro, 128gb (als Neu!)'...
[DEBUG]  -> effective ad meta:
active: true
type: OFFER
title: iPhone 14 Pro, 128gb (als Neu!)
description: "Wird immer in einer Handytasche und einem Schutzglas getragen.\nAkku:
  89%.\nDie Box hat sogar noch die ursprüngliche Folie auf dem Glas, so dass es aussieht
  wie neu\n\n----\n\nAlways carried in a phone case and protective glass.\nBattery:
  89%.\nThe box even still has the original foil on the glass, so it looks like new"
category: 161/173
special_attributes:
  art_s: apple
  device_equipment_s: only_device
  condition_s: like_new
  color_s: schwarz
price: 625
price_type: FIXED
shipping_type: SHIPPING
shipping_costs: '4.50'
shipping_options:
- Hermes_Päckchen
sell_directly: true
images:
- /Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907194386/ad_2907194386__img1.jpg
- /Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907194386/ad_2907194386__img2.jpg
- /Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907194386/ad_2907194386__img3.jpg
- /Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907194386/ad_2907194386__img4.jpg
- /Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907194386/ad_2907194386__img5.jpg
- /Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907194386/ad_2907194386__img6.jpg
- /Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907194386/ad_2907194386__img7.jpg
- /Users/sasha/code/kleinanzeigen/downloaded-ads/ad_2907194386/ad_2907194386__img8.jpg
contact:
  zipcode: '10115'
  name: Aleks
  street:
  phone:
id: 2927808927
created_on: '2024-10-29T00:00:00'
updated_on: '2024-11-19T19:51:42.775640'
republication_interval: 7
[DEBUG]  -> Opening [https://www.kleinanzeigen.de/p-anzeige-aufgeben-schritt2.html]...
[INFO]  ... pausing for 2380 ms ...
[INFO]  ... pausing for 1972 ms ...
[INFO]  ... pausing for 1738 ms ...
[INFO]  ... pausing for 2171 ms ...
[DEBUG]  -> Opening [https://www.kleinanzeigen.de/p-kategorie-aendern.html#?path=161/173]...
[DEBUG]  ... pausing for 1327 ms ...
[DEBUG] Found 4 special attributes
[DEBUG] Setting special attribute [art_s] to [apple]...
[INFO]  ... pausing for 2481 ms ...
[DEBUG] Successfully set attribute field [art_s] to [apple]...
[DEBUG] Setting special attribute [device_equipment_s] to [only_device]...
[DEBUG]  ... pausing for 1249 ms ...
[DEBUG] Successfully set attribute field [device_equipment_s] to [only_device]...
[DEBUG]  ... pausing for 1455 ms ...
[INFO]  ... pausing for 1881 ms ...
[INFO]  ... pausing for 1974 ms ...
[DEBUG] Setting special attribute [color_s] to [schwarz]...
[DEBUG]  ... pausing for 1098 ms ...
[DEBUG] Successfully set attribute field [color_s] to [schwarz]...
[DEBUG] Closing Browser session...
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot/__main__.py", line 9, in <module>
  File "kleinanzeigen_bot/__init__.py", line 945, in main
  File "asyncio/base_events.py", line 721, in run_until_complete
  File "kleinanzeigen_bot/__init__.py", line 92, in run
  File "kleinanzeigen_bot/__init__.py", line 506, in publish_ads
  File "kleinanzeigen_bot/__init__.py", line 567, in publish_ad
  File "kleinanzeigen_bot/web_scraping_mixin.py", line 341, in web_click
  File "kleinanzeigen_bot/web_scraping_mixin.py", line 378, in web_find
  File "kleinanzeigen_bot/web_scraping_mixin.py", line 285, in web_await
TimeoutError: No HTML element found using CSS selector '[class*="jsx-2623555103"]' within 5 seconds.

[PYI-754:ERROR] Failed to execute script '__main__' due to unhandled exception!
successfully removed temp profile /var/folders/5_/3s57744n5mn067f_87cxytrc0000gn/T/uc_p0qlnwhf
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hendrikator** [comment]
same issue

**Comment by Synzed** [comment]
Same, selectors seem to be messed up and need an update
