### ISSUE TITLE
g2478014: Can't publish any ads

### ISSUE THREAD

**Issue by jniggemann** [Second-Hand-Friends/kleinanzeigen-bot#38]
Updated to lastest version 0.1.dev1+g2478014, can't publish any ads. Edit: brand-new 1d5fc64 doesn't work either.

No config change, no ad changes, Edge (v99).

Error is always `NoSuchElementException: Message: None`

I also deleted the older versions I kept - perhaps we ought to keep old pre-releases online?

**Comment by jniggemann** [comment]
Looking at the running browser I can see that the ad title and category are correctly set. Maybe something with uploading images?

**Comment by sebthom** [comment]
Hm... works fine for me I just published ads.

Can you run it with --verbose flag?

**Comment by jniggemann** [comment]
```
2022-03-12 14:24:34,131 [INFO] Processing 1/14: 'Beamer' from [D:\Programme\ebay\ads\ad_beamer.yml]...
2022-03-12 14:24:34,131 [INFO] Deleting ad 'Beamer' if already present...
2022-03-12 14:24:34,131 [DEBUG]  -> Opening [https://www.ebay-kleinanzeigen.de/m-meine-anzeigen.html]...
2022-03-12 14:24:34,147 [DEBUG]   => skipping, [https://www.ebay-kleinanzeigen.de/m-meine-anzeigen.html] is already open
2022-03-12 14:24:34,147 [INFO]  ... pausing for 2000 ms ...
2022-03-12 14:24:36,198 [DEBUG]  -> HTTP GET [https://www.ebay-kleinanzeigen.de/m-meine-anzeigen-verwalten.json?sort=DEFAULT]...
2022-03-12 14:24:36,542 [INFO] Publishing ad 'Beamer'...
2022-03-12 14:24:36,542 [DEBUG]  -> effective ad meta:
2022-03-12 14:24:36,588 [DEBUG]  -> Opening [https://www.ebay-kleinanzeigen.de/p-anzeige-aufgeben-schritt2.html]...
2022-03-12 14:24:38,522 [INFO]  ... pausing for 2000 ms ...
2022-03-12 14:24:40,651 [DEBUG]  ... pausing for 282 ms ...
2022-03-12 14:24:41,027 [DEBUG]  ... pausing for 665 ms ...
2022-03-12 14:24:42,831 [INFO]  ... pausing for 1655 ms ...
2022-03-12 14:24:49,553 [ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot\selenium_mixin.py", line 192, in web_await
  File "selenium\webdriver\support\wait.py", line 89, in until
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x012A9943+2595139]
	Ordinal0 [0x0123C9F1+2148849]
	Ordinal0 [0x01134528+1066280]
	Ordinal0 [0x01160FD4+1249236]
	Ordinal0 [0x011611CB+1249739]
	Ordinal0 [0x0118D812+1431570]
	Ordinal0 [0x0117BA34+1358388]
	Ordinal0 [0x0118BAF2+1424114]
	Ordinal0 [0x0117B806+1357830]
	Ordinal0 [0x01156086+1204358]
	Ordinal0 [0x01156F96+1208214]
	GetHandleVerifier [0x0144B232+1658114]
	GetHandleVerifier [0x0150312C+2411516]
	GetHandleVerifier [0x0133F261+560433]
	GetHandleVerifier [0x0133E366+556598]
	Ordinal0 [0x0124286B+2173035]
	Ordinal0 [0x012475F8+2192888]
	Ordinal0 [0x012476E5+2193125]
	Ordinal0 [0x012511FC+2232828]
	BaseThreadInitThunk [0x74AB8674+36]
	RtlGetAppContainerNamedObjectPath [0x77E35EC7+311]
	RtlGetAppContainerNamedObjectPath [0x77E35E97+263]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 8, in <module>
  File "kleinanzeigen_bot\__init__.py", line 541, in main
  File "kleinanzeigen_bot\__init__.py", line 76, in run
  File "kleinanzeigen_bot\__init__.py", line 353, in publish_ads
  File "kleinanzeigen_bot\__init__.py", line 392, in publish_ad
  File "kleinanzeigen_bot\selenium_mixin.py", line 223, in web_find
  File "kleinanzeigen_bot\selenium_mixin.py", line 196, in web_await
selenium.common.exceptions.NoSuchElementException: Message: None
```

**Comment by sebthom** [comment]
Can you please retry with the latest build and paste the log

**Comment by jniggemann** [comment]
Thank you so much, it works again.
Would you like the log anyway?
