### ISSUE TITLE
end user test on macos

### ISSUE THREAD

**Issue by sebthom** [Second-Hand-Friends/kleinanzeigen-bot#6]
The app should be tested on macos (incl. publishing some ads) to verify it's functionality.

**Comment by DenisLanz** [comment]
I tried to publish my first offer on mac and stumbled over the following issue
```
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_101.0.4930
```
might be related to edge not beeing present, just chrome and or chromium.

**Comment by sebthom** [comment]
This should also work with chrome/chromium. Is your browser on the PATH? If not, what happens when you directly add it to the config.yaml?

```yaml
browser:
  binary_location: "/path/to/chrome"
```

**Comment by DenisLanz** [comment]
Chrome is on my PATH, but I added it to the config just in case. Now I get the following error:

```
[ERROR] Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/<username>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/__main__.py", line 8, in <module>
    kleinanzeigen_bot.main(sys.argv)
  File "/Users/<username>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 575, in main
    KleinanzeigenBot().run(args)
  File "/Users/<username>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 75, in run
    self.create_webdriver_session()
  File "/Users/<username>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/selenium_mixin.py", line 115, in create_webdriver_session
    chrome_major_version = chrome_version.split(".", 1)[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by sebthom** [comment]
@DenisLanz can you try the latest release please, I tried to improve the browser configuration.

**Comment by DenisLanz** [comment]
Tried the latest release, no luck, but after I installed chromedriver through homebrew  I was able to publish my first offer. Is that a mainly coincidence, mac specific, should it work without chromedriver or just missing in the documentation?

**Comment by sebthom** [comment]
Manual installation of Chromedriver should not be required. The app is supposed to install the matching one automatically.

Can you please attach a full log of an attempt when publishing fails. Please use the `--verbose` mode. Thank you!

**Comment by DenisLanz** [comment]
Alright, removed the chromedrive again. Doesn't work anymore. Here is the log:

``` bash
[INFO] Loaded 1 ad
[INFO] Creating WebDriver session...
[INFO] Using Browser: CHROMIUM 101.0.4930 [/Applications/Chromium.app/Contents/MacOS/Chromium]


[INFO]

====== WebDriver manager ======
[INFO] ====== WebDriver manager ======
Current chromium version is 101.0.4930
[INFO] Current chromium version is 101.0.4930
Get LATEST chromedriver version for 101.0.4930 chromium
[INFO] Get LATEST chromedriver version for 101.0.4930 chromium
[ERROR] Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/__main__.py", line 8, in <module>
    kleinanzeigen_bot.main(sys.argv)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 575, in main
    KleinanzeigenBot().run(args)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 75, in run
    self.create_webdriver_session()
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/selenium_mixin.py", line 135, in create_webdriver_session
    webdriver_path = webdriver_mgr.install()
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/manager.py", line 19, in _get_driver_path
    binary_path = self.driver_cache.find_driver(driver)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/driver_cache.py", line 74, in find_driver
    driver_version = driver.get_version()
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/driver.py", line 39, in get_version
    self.get_latest_release_version()
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/driver.py", line 76, in get_latest_release_version
    validate_response(resp)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/utils.py", line 90, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_101.0.4930

```

**Comment by sebthom** [comment]
I tried to improve the driver download. plesse give the latest build a try.

**Comment by DenisLanz** [comment]
Same issue unfortunately, is there anything I could help you with?

```bash
[INFO] Loaded 1 ad
[INFO] Creating WebDriver session...
[INFO] Using Browser: CHROMIUM 101.0.4930 [/Applications/Chromium.app/Contents/MacOS/Chromium]


[INFO]

====== WebDriver manager ======
[INFO] ====== WebDriver manager ======
Get LATEST chromedriver version for 101 chromium
[INFO] Get LATEST chromedriver version for 101 chromium
[ERROR] Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/__main__.py", line 8, in <module>
    kleinanzeigen_bot.main(sys.argv)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 584, in main
    KleinanzeigenBot().run(args)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/__init__.py", line 75, in run
    self.create_webdriver_session()
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/kleinanzeigen_bot/selenium_mixin.py", line 136, in create_webdriver_session
    webdriver_path = webdriver_mgr.install()
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/manager.py", line 19, in _get_driver_path
    binary_path = self.driver_cache.find_driver(driver)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/driver_cache.py", line 74, in find_driver
    driver_version = driver.get_version()
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/driver.py", line 39, in get_version
    self.get_latest_release_version()
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/driver.py", line 76, in get_latest_release_version
    validate_response(resp)
  File "/Users/<userfolder>/Documents/github.com/Second-Hand-Friends/kleinanzeigen-bot/__pypackages__/3.10/lib/webdriver_manager/utils.py", line 90, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_101

 FAIL: 1
```

**Comment by sebthom** [comment]
I think your browser is too new. There is no chromedriver for version 101 at https://chromedriver.storage.googleapis.com/

**Comment by DenisLanz** [comment]
Well - just installed the latest Chromium from the homebrew cask. As far as I can see the homebrew cask for chromedriver just falls back to the latest release on https://chromedriver.storage.googleapis.com/LATEST_RELEASE if there is no matching version. Would that be an option here as well?

**Comment by DenisLanz** [comment]
Alright, I switched to Google Chrome - as Chromium did not really work reliably even with the manual install of chromedriver. Now it works flawlessly. What I noticed is da I've to put the binary path in quotation marks as escaping spaces from Google\ Chrome.app isn't working when I just copy the path from pwd.

**Comment by sebthom** [comment]
Could be that the latest chromedriver  has compatibility issues with chromium 101. Is the chrome version you are using older?

**Comment by DenisLanz** [comment]
Yes Chrome is currently at 99.

**Comment by DenisLanz** [comment]
I would consider end-user tests as successful on macOS. I've been publishing ads the last couple of weeks and there is nothing that I would say that is a specific issue related to macOS.

**Comment by sebthom** [comment]
Ok, thanks for the feedback!
