### ISSUE TITLE
Failed to execute script '__main__' due to unhandled exception!

### ISSUE THREAD

**Issue by dragonheart100** [Second-Hand-Friends/kleinanzeigen-bot#82]
Problem with republishing ads:

`[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 8, in <module>
  File "kleinanzeigen_bot\__init__.py", line 506, in main
  File "kleinanzeigen_bot\__init__.py", line 76, in run
  File "kleinanzeigen_bot\__init__.py", line 341, in publish_ads
  File "kleinanzeigen_bot\__init__.py", line 422, in publish_ad
  File "kleinanzeigen_bot\selenium_mixin.py", line 225, in web_input
  File "selenium\webdriver\remote\webelement.py", line 93, in clear
  File "selenium\webdriver\remote\webelement.py", line 710, in _execute
  File "selenium\webdriver\remote\webdriver.py", line 424, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
selenium.common.exceptions.InvalidElementStateException: Message: invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=102.0.5005.63)
Stacktrace:
Backtrace:
        Ordinal0 [0x00C1D953+2414931]
        Ordinal0 [0x00BAF5E1+1963489]
        Ordinal0 [0x00A9C6B8+837304]
        Ordinal0 [0x00A9F0B4+848052]
        Ordinal0 [0x00A9EF72+847730]
        Ordinal0 [0x00A9F200+848384]
        Ordinal0 [0x00AC1D4D+990541]
        Ordinal0 [0x00AE449C+1131676]
        Ordinal0 [0x00ABFC74+982132]
        Ordinal0 [0x00AE46B4+1132212]
        Ordinal0 [0x00AF4812+1198098]
        Ordinal0 [0x00AE42B6+1131190]
        Ordinal0 [0x00ABE860+976992]
        Ordinal0 [0x00ABF756+980822]
        GetHandleVerifier [0x00E8CC62+2510274]
        GetHandleVerifier [0x00E7F760+2455744]
        GetHandleVerifier [0x00CAEABA+551962]
        GetHandleVerifier [0x00CAD916+547446]
        Ordinal0 [0x00BB5F3B+1990459]
        Ordinal0 [0x00BBA898+2009240]
        Ordinal0 [0x00BBA985+2009477]
        Ordinal0 [0x00BC3AD1+2046673]
        BaseThreadInitThunk [0x777CFA29+25]
        RtlGetAppContainerNamedObjectPath [0x779C7A7E+286]
        RtlGetAppContainerNamedObjectPath [0x779C7A4E+238]

[3112] Failed to execute script '__main__' due to unhandled exception!`

**Comment by sebthom** [comment]
Please try the latest build.

**Comment by dragonheart100** [comment]
Thanks it worked again! :)

**Comment by dragonheart100** [comment]
I have the same error again, can you help please?
If you need further information, let me know.

[INFO]  ... pausing for 2000 ms ...
[15340:18864:0809/002815.389:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
[INFO]  ... pausing for 1799 ms ...
[15340:18864:0809/002819.210:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
[INFO]  ... pausing for 2000 ms ...
[INFO]  ... pausing for 2000 ms ...
[15340:18864:0809/002826.614:ERROR:stun_port.cc(80)] Binding error response: class=4 number=1 reason=Unauthorized
[ERROR] ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=103.0.5060.134)
Stacktrace:
Backtrace:
        Ordinal0 [0x00B95FD3+2187219]
        Ordinal0 [0x00B2E6D1+1763025]
        Ordinal0 [0x00A43D40+802112]
        Ordinal0 [0x00A72C03+994307]
        Ordinal0 [0x00A689B3+952755]
        Ordinal0 [0x00A8CB8C+1100684]
        Ordinal0 [0x00A68394+951188]
        Ordinal0 [0x00A8CDA4+1101220]
        Ordinal0 [0x00A9CFC2+1167298]
        Ordinal0 [0x00A8C9A6+1100198]
        Ordinal0 [0x00A66F80+946048]
        Ordinal0 [0x00A67E76+949878]
        GetHandleVerifier [0x00E390C2+2721218]
        GetHandleVerifier [0x00E2AAF0+2662384]
        GetHandleVerifier [0x00C2137A+526458]
        GetHandleVerifier [0x00C20416+522518]
        Ordinal0 [0x00B34EAB+1789611]
        Ordinal0 [0x00B397A8+1808296]
        Ordinal0 [0x00B39895+1808533]
        Ordinal0 [0x00B426C1+1844929]
        BaseThreadInitThunk [0x774DFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77687A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77687A6E+238]

[17572] Failed to execute script '__main__' due to unhandled exception!

**Comment by dragonheart100** [comment]
Thank you very much - thats it!
You saved my life :D
